#!/usr/bin/env python3
"""
Hub project discovery — REPORT-ONLY.

Scans the workspace for projects, classifies each (new / scaffolded / active),
and writes the registry at the-owl/.devflow/projects.yaml. It NEVER mutates any
project — it only reads the filesystem + git and writes the-owl's own registry.
Deterministic (no LLM) by design — this is the crystallized, reproducible half;
the `project-registry` skill wraps it.
"""
import os, subprocess, datetime
from collections import Counter

WORKSPACE = "/Users/rafaelribeiro/Evolve Labs/Evolve Labs"
OWL = os.path.join(WORKSPACE, "the-owl")
REGISTRY = os.path.join(OWL, ".devflow", "projects.yaml")
SKIP = {"node_modules", ".git", ".next", "dist", "build", "__pycache__", ".venv", "venv", "target", "vendor"}
ACTIVE_MIN_COMMITS = 10  # git history threshold for "active" (owner-confirmed: git-based)


def git(path, *args):
    try:
        r = subprocess.run(["git", "-C", path, *args], capture_output=True, text=True, timeout=10)
        return r.stdout.strip()
    except Exception:
        return ""


def find_project_roots(root, maxdepth=3):
    """A project root = a dir with .git/ (a real repo) or .claude/ or .devflow/.
    A `.git` dir is a hard boundary (don't descend into a repo). A `.claude`/`.devflow`-only
    dir is recorded but we KEEP recursing — it may be a container (e.g. `Projects/` with its
    own .claude that holds nested git projects). Afterwards, drop any recorded dir that is an
    ancestor of another recorded dir (a container shadowing its real projects)."""
    roots = []

    def walk(d, depth):
        if depth > maxdepth:
            return
        has_git = os.path.isdir(os.path.join(d, ".git"))
        has_marker = has_git or os.path.isdir(os.path.join(d, ".claude")) or os.path.isdir(os.path.join(d, ".devflow"))
        if d != WORKSPACE and has_marker:
            roots.append(d)
        if has_git:
            return  # git repo = boundary; don't descend
        try:
            entries = sorted(os.listdir(d))
        except OSError:
            return
        for e in entries:
            if e.startswith(".") or e in SKIP:
                continue
            p = os.path.join(d, e)
            if os.path.isdir(p):
                walk(p, depth + 1)

    walk(root, 0)
    # Drop container ancestors (a recorded dir that contains another recorded dir).
    return [r for r in roots if not any(o != r and o.startswith(r + os.sep) for o in roots)]


def classify(p):
    has_claude = os.path.isdir(os.path.join(p, ".claude"))
    has_devflow = os.path.isdir(os.path.join(p, ".devflow"))
    has_docs = os.path.isdir(os.path.join(p, "docs"))
    is_git = os.path.isdir(os.path.join(p, ".git"))
    commits, last = 0, ""
    if is_git:
        c = git(p, "rev-list", "--count", "HEAD")
        commits = int(c) if c.isdigit() else 0
        last = git(p, "log", "-1", "--format=%cs")
    if is_git and commits >= ACTIVE_MIN_COMMITS:
        state = "active"
    elif has_claude or has_devflow:
        state = "scaffolded"
    else:
        state = "new"
    return dict(has_claude=has_claude, has_devflow=has_devflow, has_docs=has_docs,
               is_git=is_git, commits=commits, last=last, state=state)


def rel(p):
    return os.path.relpath(p, WORKSPACE)


def main():
    roots = sorted(find_project_roots(WORKSPACE), key=rel)
    infos = [(p, classify(p)) for p in roots]

    out = [
        "# projects.yaml — Hub project registry (managed by the-owl).",
        "# Generated by .claude/skills/project-registry/discover.py — REPORT-ONLY (never mutates a project).",
        "# Regenerate: python3 .claude/skills/project-registry/discover.py  (or the /project-registry skill).",
        f"generated: {datetime.date.today().isoformat()}",
        f'workspace: "{WORKSPACE}"',
        f"count: {len(infos)}",
        "# state: active (git history >= %d) · scaffolded (has .claude/.devflow, light) · new (bare)" % ACTIVE_MIN_COMMITS,
        "projects:",
    ]
    for p, c in infos:
        out += [
            f"  - name: {os.path.basename(p)}",
            f'    path: "{rel(p)}"',
            f"    state: {c['state']}",
            f"    has_claude: {str(c['has_claude']).lower()}",
            f"    has_devflow: {str(c['has_devflow']).lower()}",
            f"    has_docs: {str(c['has_docs']).lower()}",
            f"    git_commits: {c['commits']}",
            f"    last_commit: {c['last'] or 'null'}",
        ]
    os.makedirs(os.path.dirname(REGISTRY), exist_ok=True)
    with open(REGISTRY, "w") as f:
        f.write("\n".join(out) + "\n")

    states = Counter(c["state"] for _, c in infos)
    print(f"Registered {len(infos)} projects -> {REGISTRY}")
    print("By state:", dict(states))
    for p, c in infos:
        print(f"  [{c['state']:9}] {rel(p)}  (commits={c['commits']}, claude={c['has_claude']}, devflow={c['has_devflow']})")


if __name__ == "__main__":
    main()
